security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'bcrypt'
            cost: 15
    providers:
        app_user_provider:
            entity:
                class: ClownMeister\BohemiaApi\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: api_login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
        admin:
            pattern: ^/
            anonymous: false
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout

    access_control:
        - { path: /api/login, roles: PUBLIC_ACCESS }
        - { path: /login,       roles: PUBLIC_ACCESS }
        - { path: /register,       roles: PUBLIC_ACCESS }
        - { path: /registration-success,       roles: PUBLIC_ACCESS }
        - { path: /verify/email,       roles: PUBLIC_ACCESS }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ~/,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ~/api,       roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
