controllers:
    resource: ../../src/Controller/
    type: annotation

api:
    resource: ../../src/Controller/Api
    type: annotation
    prefix: api/v1

kernel:
    resource: ../../src/Kernel.php
    type: annotation
