parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  ClownMeister\BohemiaApi\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

#  security.role_hierarchy:
#    class: ClownMeister\BohemiaApi\Security\RoleHierarchy
#    public: false
